### ISSUE TITLE
The main method

### ISSUE THREAD

**Issue by ariG23498** [RoyARG02/soil_moisture_app#14]
The main method still takes up time, it is not async. All the api endpoints are fetched and then the runApp is triggered, I am guessing a synchronisation error in any of the classes or methods that is made. @RoyARG02

**Comment by royarg02** [comment]
The app runs and fetches api in the following manner:
1. *Wait* till orientation lock to portrait.
2. *Then* run the app.
3. *Wait* till MediaQuery gives non-zero size value.
4. *Then wait* till current data fetched.
5. *Then* async fetch threshold values.
6. Async fetch analysis values.

Steps 1, 2 are completed during the splash screen.
Step 3 is completed during the *extended* splash screen.
Step 4 is completed after invoking Overview page with the help of FutureBuilder.
Step 5, 6 are invoked after current data is fetched.

The app takes *approx.* 10 sec to finish fetching the current data **on first run** and then takes 2-3 sec on subsequent launch.

Further tests on API fetching may be required.
