### ISSUE TITLE
Moisture percentage resets when changing pages

### ISSUE THREAD

**Issue by royarg02** [RoyARG02/soil_moisture_app#5]
Need to somehow keep the previous page alive to avoid resetting.

**Comment by royarg02** [comment]
Keeping the scroll position in memory would also be a nice bonus.

**Comment by ariG23498** [comment]
I think, as the app takes random values now, it resets now, but when we will take the API values, it might not reset. Still in question.

**Comment by royarg02** [comment]
API linked, does not reset ^_^.
