### ISSUE TITLE
Multi-colored segregated progress bars

### ISSUE THREAD

**Issue by royarg02** [RoyARG02/soil_moisture_app#7]
Need help to implement segregated progress bars, each having their own color.

**Comment by ariG23498** [comment]
Could you be more specific in this issue? @RoyARG02

**Comment by royarg02** [comment]
The current implementation of progress bars for moisture content can take only one color.
Although it is enough for showing only the _current_ moisture content, (whether it is very low for adequate irrigation, or not), it cannot be used in case one needs to know the _increment/decrement_ of moisture from the previous day/ time. For this case a suitable progress bar could be used which shows two segments of different colors (say **red** for _decrement_ and **blue** for _increment_ from the previous readings).

I am unable to find any Flutter API/ packages that achieves the same.

**Comment by royarg02** [comment]
Feature scrapped.
